TourManagementSystem/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace TourManagementSystem.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TourManagementSystem/Controllers/OffersController.cs
using Microsoft.AspNetCore.Mvc;

namespace TourManagementSystem.Controllers
{
    public class OffersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TourManagementSystem/Views/About/Index.cshtml
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from themewagon.github.io/VoyagePro/about.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 28 Mar 2025 12:26:56 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
	<title>About Us</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="VoyagePro Project">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="styles/bootstrap4/bootstrap.min.css">
	<link href="plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type="text/css" href="plugins/OwlCarousel2-2.2.1/owl.carousel.css">
	<link rel="stylesheet" type="text/css" href="plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
	<link rel="stylesheet" type="text/css" href="plugins/OwlCarousel2-2.2.1/animate.css">
	<link rel="stylesheet" type="text/css" href="styles/about_styles.css">
	<link rel="stylesheet" type="text/css" href="styles/about_responsive.css">
</head>

<body>

	<div class="super_container">

		<!-- Home -->

		<div class="home">
			<div class="home_background parallax-window" data-parallax="scroll" data-image-src="images/about_background.jpg"></div>
			<div class="home_content">
				<div class="home_title">about us</div>
			</div>
		</div>

		<!-- Intro -->

		<div class="intro">
			<div class="container">
				<div class="row">
					<div class="col-lg-7">
						<div class="intro_image"><img src="images/intro.png" alt=""></div>
					</div>
					<div class="col-lg-5">
						<div class="intro_content">
							<div class="intro_title">we have the best tours</div>
							<p class="intro_text">Discover unforgettable journeys with VOYAGEPRO. Our expertly crafted adventures take you to breathtaking destinations with seamless planning. From hidden beaches to cultural gems, every detail is perfected for your dream getaway. Travel confidently with our 24/7 support and sustainable approach. Your extraordinary experience begins here.</p>
							<div class="button intro_button"><div class="button_bcg"></div><a asp-controller="Offers" asp-action="Index">explore now<span></span><span></span><span></span></a></div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Stats -->

		<div class="stats">
			<div class="container">
				<div class="row">
					<div class="col text-center">
						<div class="section_title">years statistics</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-10 offset-lg-1 text-center">
						<p class="stats_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis vulputate eros, iaculis consequat nisl. Nunc et suscipit urna. Integer elementum orci eu vehicula pretium. Donec bibendum tristique condimentum. Aenean in lacus ligula. </p>
					</div>
				</div>
				<div class="row">
					<div class="col">
						<div class="stats_years">
							<div class="stats_years_last">2016</div>
							<div class="stats_years_new float-right">2017</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col">
						<div class="stats_contents">

							<!-- Stats Item -->
							<div class="stats_item d-flex flex-md-row flex-column clearfix">
								<div class="stats_last order-md-1 order-3">
									<div class="stats_last_icon d-flex flex-column align-items-center justify-content-end">
										<img src="images/stats_1.png" alt="">
									</div>
									<div class="stats_last_content">
										<div class="stats_number">1642</div>
										<div class="stats_type">Clients</div>
									</div>
								</div>
								<div class="stats_bar order-md-2 order-2" data-x="1642" data-y="3527" data-color="#31124b">
									<div class="stats_bar_perc">
										<div>
											<div class="stats_bar_value"></div>
										</div>
									</div>
								</div>
								<div class="stats_new order-md-3 order-1 text-right">
									<div class="stats_new_icon d-flex flex-column align-items-center justify-content-end">
										<img src="images/stats_1.png" alt="">
									</div>
									<div class="stats_new_content">
										<div class="stats_number">3527</div>
										<div class="stats_type">Clients</div>
									</div>
								</div>
							</div>

							<!-- Stats Item -->
							<div class="stats_item d-flex flex-md-row flex-column clearfix">
								<div class="stats_last order-md-1 order-3">
									<div class="stats_last_icon d-flex flex-column align-items-center justify-content-end">
										<img src="images/stats_2.png" alt="">
									</div>
									<div class="stats_last_content">
										<div class="stats_number">768</div>
										<div class="stats_type">Returning Clients</div>
									</div>
								</div>
								<div class="stats_bar order-md-2 order-2" data-x="768" data-y="145" data-color="#a95ce4">
									<div class="stats_bar_perc">
										<div>
											<div class="stats_bar_value"></div>
										</div>
									</div>
								</div>
								<div class="stats_new order-md-3 order-1 text-right">
									<div class="stats_new_icon d-flex flex-column align-items-center justify-content-end">
										<img src="images/stats_2.png" alt="">
									</div>
									<div class="stats_new_content">
										<div class="stats_number">145</div>
										<div class="stats_type">Returning Clients</div>
									</div>
								</div>
							</div>

							<!-- Stats Item -->
							<div class="stats_item d-flex flex-md-row flex-column clearfix">
								<div class="stats_last order-md-1 order-3">
									<div class="stats_last_icon d-flex flex-column align-items-center justify-content-end">
										<img src="images/stats_3.png" alt="">
									</div>
									<div class="stats_last_content">
										<div class="stats_number">11546</div>
										<div class="stats_type">Reach</div>
									</div>
								</div>
								<div class="stats_bar order-md-2 order-2" data-x="11546" data-y="9321" data-color="#fa6f1b">
									<div class="stats_bar_perc">
										<div>
											<div class="stats_bar_value"></div>
										</div>
									</div>
								</div>
								<div class="stats_new order-md-3 order-1 text-right">
									<div class="stats_new_icon d-flex flex-column align-items-center justify-content-end">
										<img src="images/stats_3.png" alt="">
									</div>
									<div class="stats_new_content">
										<div class="stats_number">9321</div>
										<div class="stats_type">Reach</div>
									</div>
								</div>
							</div>

							<!-- Stats Item -->
							<div class="stats_item d-flex flex-md-row flex-column clearfix">
								<div class="stats_last order-md-1 order-3">
									<div class="stats_last_icon d-flex flex-column align-items-center justify-content-end">
										<img src="images/stats_4.png" alt="">
									</div>
									<div class="stats_last_content">
										<div class="stats_number">3729</div>
										<div class="stats_type">Items</div>
									</div>
								</div>
								<div class="stats_bar order-md-2 order-2" data-x="3729" data-y="17429" data-color="#fa9e1b">
									<div class="stats_bar_perc">
										<div>
											<div class="stats_bar_value"></div>
										</div>
									</div>
								</div>
								<div class="stats_new order-md-3 order-1 text-right">
									<div class="stats_new_icon d-flex flex-column align-items-center justify-content-end">
										<img src="images/stats_4.png" alt="">
									</div>
									<div class="stats_new_content">
										<div class="stats_number">17429</div>
										<div class="stats_type">More Items</div>
									</div>
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Add -->

		<div class="add">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="add_container">
							<div class="add_background" style="background-image:url(images/add.jpg)"></div>
							<div class="add_content">
								<h1 class="add_title">thailand</h1>
								<div class="add_subtitle">From <span>$999</span></div>
								<div class="button add_button"><div class="button_bcg"></div><a asp-controller="Offers" asp-action="Index">explore now<span></span><span></span><span></span></a></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Milestones -->

		<div class="milestones">
			<div class="container">
				<div class="row">

					<!-- Milestone -->
					<div class="col-lg-3 milestone_col">
						<div class="milestone text-center">
							<div class="milestone_icon"><img src="images/milestone_1.png" alt=""></div>
							<div class="milestone_counter" data-end-value="255">0</div>
							<div class="milestone_text">Clients</div>
						</div>
					</div>

					<!-- Milestone -->
					<div class="col-lg-3 milestone_col">
						<div class="milestone text-center">
							<div class="milestone_icon"><img src="images/milestone_2.png" alt=""></div>
							<div class="milestone_counter" data-end-value="1176">0</div>
							<div class="milestone_text">Projects</div>
						</div>
					</div>

					<!-- Milestone -->
					<div class="col-lg-3 milestone_col">
						<div class="milestone text-center">
							<div class="milestone_icon"><img src="images/milestone_3.png" alt=""></div>
							<div class="milestone_counter" data-end-value="39">0</div>
							<div class="milestone_text">Countries</div>
						</div>
					</div>

					<!-- Milestone -->
					<div class="col-lg-3 milestone_col">
						<div class="milestone text-center">
							<div class="milestone_icon"><img src="images/milestone_4.png" alt=""></div>
							<div class="milestone_counter" data-end-value="127">0</div>
							<div class="milestone_text">Coffees</div>
						</div>
					</div>

				</div>
			</div>
		</div>



	</div>

	<script src="js/jquery-3.2.1.min.js"></script>
	<script src="styles/bootstrap4/popper.js"></script>
	<script src="styles/bootstrap4/bootstrap.min.js"></script>
	<script src="plugins/greensock/TweenMax.min.js"></script>
	<script src="plugins/greensock/TimelineMax.min.js"></script>
	<script src="plugins/scrollmagic/ScrollMagic.min.js"></script>
	<script src="plugins/greensock/animation.gsap.min.js"></script>
	<script src="plugins/greensock/ScrollToPlugin.min.js"></script>
	<script src="plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
	<script src="plugins/easing/easing.js"></script>
	<script src="plugins/parallax-js-master/parallax.min.js"></script>
	<script src="js/about_custom.js"></script>

</body>


<!-- Mirrored from themewagon.github.io/VoyagePro/about.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 28 Mar 2025 12:27:01 GMT -->
</html>